extends: airbnb
env:
  browser: true
  node: true
  mocha: true
rules:
  strict: 0
  no-console: 0
  no-use-before-define: 0
  arrow-parens: ["error", "as-needed"]
  no-mixed-operators: 0
  object-curly-newline: 0
